package io.github.d1bg.gs.core.input;

public enum Action {
    DEMO_INCREASE_ALPHA,
    DEMO_DECREASE_ALPHA,

    CAMERA_MOVE_FORWARD,
    CAMERA_MOVE_BACKWARD,
    CAMERA_MOVE_LEFT,
    CAMERA_MOVE_RIGHT,

    CAMERA_ROTATE_UP,
    CAMERA_ROTATE_DOWN,
    CAMERA_ROTATE_LEFT,
    CAMERA_ROTATE_RIGHT,

    LOCK_CURSOR
}
